name: Deploy Application to EC2 via SSH

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image to Docker Hub
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}"
          echo "Building image: $IMAGE"
          docker build -t $IMAGE .
          echo "Pushing image..."
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}          # Your EC2 IPv4 address
          username: ubuntu                       # Default user for Ubuntu AMIs
          key: ${{ secrets.EC2_SSH_KEY }}        # Your private SSH key (PEM contents)
          script: |
            IMAGE="${{ env.IMAGE }}"
            echo "Pulling latest image: $IMAGE"
            docker pull $IMAGE

            echo "Stopping old container..."
            docker ps -aq --filter "name=app" | xargs -r docker rm -f

            echo "Starting new container..."
            docker run -d --name app \
              -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }} \
              -p 8080:8080 \
              $IMAGE
